#+TITLE: ECFPAW (Emacs Configuration For Programming and Writing).
#+AUTHOR: tusharhero
#+email: tusharhero@sdf.org

Welcome to my GNU Emacs configuration repository. You can find the
configuration [[file:config.org][here]].

I will use this configuration primarily for programming and writing
articles and stories. And it is for me, I would discourage you to use
my configuration. I have put it here publicly for easy access. You
might learn something if you are /completely/ new though.

Before writing this, I used to use Spacemacs, and I think spacemacs is
great too, I am going to get configure some features from spacemacs
here as well (The ones I liked obviously).

* Setup

I am going to use it in GNU Linux only (I hope), and here the setup is
quite simple.

- Install GNU Emacs using your package manager,
  for me its Archlinux
  #+begin_src bash
    sudo pacman -S emacs
  #+end_src
- Get the configuration in the right place, 
  #+begin_src bash
    git clone https://github.com/tusharhero/ECFPAW ~/.config/emacs
  #+end_src
- enable the Emacs server and start it.
  #+begin_src bash
    systemctl enable emacs --user
    systemctl start emacs --user
  #+end_src
- Run emacs using emacsclient
  #+begin_src bash
    emacsclient -nc
  #+end_src
  You can use a GUI shortcut for Emacsclient as well.

* Pains
I want to document some workarounds to make it work sometime.
** KDE
For some reason, just setting up a Emacs server =systemctl= service file doesn't
let me use =emacsclient= in GUI mode. So I had to hack my way
through. I wrote a script called =emac=.
#+begin_src bash
  #!/bin/sh 
  systemctl restart emacs --user
#+end_src
and made it auto start using KDE Plasma's settings options.

And it worked!
